const e = encodeURIComponent;

export const R = {
  auth: {
    login: "accounts/Login",
    logout: "accounts/Logout",
    refresh: "accounts/Refresh",
    me: "accounts/me",
  },
  users: {
    root: "users",
    byId: (id: number) => `users/${id}`,
    active: (id: number) => `users/${id}/active`,
    password: (id: number) => `users/${id}/password`,
    roles: "users/roles",
    claims: "users/claims",
  },
  companies: {
    root: "companies",
    byId: (id: number) => `companies/${id}`,
    name: (name: string) => `companies/name/${e(name)}`,
    alias: (alias: string) => `companies/alias/${e(alias)}`,
  },
  plans: {
    root: "plans",
    byId: (id: number) => `plans/${id}`,
    name: (name: string) => `plans/name/${e(name)}`,
    byStartYear: "plans/by-start-year",
    byEndYear: "plans/by-end-year",
  },
  states: {
    root: "states",
    byId: (id: number) => `states/${id}`,
    name: (name: string) => `states/name/${e(name)}`,
  },
  details: {
    root: "details",
    byId: (id: number) => `details/${id}`,
    name: (name: string) => `details/name/${e(name)}`,
    code: (code: string) => `details/code/${e(code)}`,
    byFunctionalFieldId: (id: number) => `details/functional-field/${id}`
  },
  functionalFields: {
    root: "functionalfields",
    byId: (id: number) => `functionalfields/${id}`,
    name: (name: string) => `functionalfields/name/${e(name)}`,
    code: (code: string) => `functionalfields/code/${e(code)}`,
    serialNumber: (sn: number) => `functionalfields/serial-number/${sn}`,
  },
  enums: {
    root: "enums",
  },
  projects: {
    root: "projects",
    summaries: "projects/summaries",
    summariesFilter: "projects/summaries/filter",
    byId: (id: number) => `projects/${id}`,
    name: (name: string) => `projects/name/${e(name)}`,
    byPlan: (id: number) => `projects/plan/${id}`,
    byCoordinator: (id: number) => `projects/coordinator-company/${id}`,
    byLeading: (id: number) => `projects/leading-company/${id}`,
    byDemanding: (id: number) => `projects/demanding-company/${id}`,
    byFunctionalField: (id: number) => `projects/functional-field/${id}`,
    byPriority: (id: number) => `projects/priority/${id}`,
    thirdSurveyScore: (score: number) => `projects/third-survey-score/${score}`,
    note: (note: string) => `projects/note/${e(note)}`,
    joint: (isJoint: boolean) => `projects/joint/${isJoint}`,
  },
  projectCompanies: {
    root: "projectcompanies",
    byId: (id: number) => `projectcompanies/${id}`,
    byProjectId: (id: number) => `projectcompanies/project/${id}`,
    byCompanyId: (id: number) => `projectcompanies/company/${id}`,
    byCategoryId: (id: number) => `projectcompanies/category/${id}`,
  },
  projectDetails: {
    root: "projectdetails",
    byId: (id: number) => `projectdetails/${id}`,
    byProjectId: (id: number) => `projectdetails/project/${id}`,
    byDetailId: (id: number) => `projectdetails/detail/${id}`,
    byDetailCountTypeId: (id: number) => `projectdetails/detail-count-type/${id}`,
    serial: (sn: number) => `projectdetails/serial/${sn}`,
    totalCount: (count: number) => `projectdetails/total-count/${count}`,
  },
  projectFiles: {
    root: "projectfiles",
    byId: (id: number) => `projectfiles/${id}`,
    download: (id: number) => `projectfiles/download/${id}`,
    byProjectId: (id: number) => `projectfiles/project/${id}`,
    byFileName: (name: string) => `projectfiles/filename/${e(name)}`,
    privacyLevel: (level: number) => `projectfiles/privacy-level/${level}`,
  },
  projectStates: {
    root: "projectstates",
    degrade: "projectstates/degrade",
    byId: (id: number) => `projectstates/${id}`,
    byProjectId: (id: number) => `projectstates/project/${id}`,
    byStateId: (id: number) => `projectstates/state/${id}`,
  },
  projectDetailCompanies: {
    root: "projectdetailcompanies",
    byId: (id: number) => `projectdetailcompanies/${id}`,
    byProjectDetailId: (id: number) => `projectdetailcompanies/project-Detail/${id}`,
    byCompanyId: (id: number) => `projectdetailcompanies/company/${id}`,
  },
  projectDetailCompanyStates: {
    root: "projectdetailcompanystates",
    byId: (id: number) => `projectdetailcompanystates/${id}`,
    byPdcId: (id: number) => `projectdetailcompanystates/project-Detail-Company/${id}`,
    byStateId: (id: number) => `projectdetailcompanystates/state/${id}`,
  },
  projectDetailCompanyYears: {
    root: "projectdetailcompanyyears",
    byId: (id: number) => `projectdetailcompanyyears/${id}`,
    byPdcId: (id: number) => `projectdetailcompanyyears/project-Detail-Company/${id}`,
    byProjectDetailId: (id: number) => `projectdetailcompanyyears/project-detail/${id}`,
    byYear: (year: number) => `projectdetailcompanyyears/year/${year}`,
  },
} as const;